<?php

namespace app\Views\Login\Avisos;

use app\Views\Login\Condicoes\CriarConta;

?>
<!doctype html>
        <html lang="en">

        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="/app/Views/Pages/assets/css/owl.carousel.min.css">
            <link rel="stylesheet" href="/app/Views/Pages/assets/css/bootstrap.min.css">
            <link rel="stylesheet" href="/app/Views/Pages/assets/css/style.css"> 
            <title>Aviso</title>
        </head>

        <body>

            <div class="half">
                <div class="bg order-1 order-md-2" style="background-image: url('/app/Views/Pages/assets/images/bg_1.jpg');"></div>
                <div class="contents order-2 order-md-1">
                    <div class="container">
                        <div class="row align-items-center justify-content-center">
                            <div class="col-md-6">
                                <div class="form-block">
                                    <div class="text-center mb-5">
                                        <h3><strong>Aviso</strong></h3>
                                    </div>
                                    <?php 
                                        $mensagem = new CriarConta();
                                        print $mensagem->imprimindoAviso();
                                    ?>
                                    <br><br><br>
                                    <form method="post">
                                        <input type="submit" name="botao_home" value="Voltar a tela inicial" class="btn btn-block btn-primary">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>