<?php

namespace app\views\login\Avisos;

use app\views\login\Condicoes\Entrar;

?>
<!doctype html>
        <html lang="en">

        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="../../view/bootstrap/fonts/icomoon/style.css">
            <link rel="stylesheet" href="../../view/bootstrap/css/owl.carousel.min.css">
            <link rel="stylesheet" href="../../view/bootstrap/css/bootstrap.min.css">
            <link rel="stylesheet" href="../../view/bootstrap/css/style.css">
            <title>Aviso</title>
        </head>

        <body>

            <div class="half">
                <div class="bg order-1 order-md-2" style="background-image: url('../../view/bootstrap/images/bg_1.jpg');"></div>
                <div class="contents order-2 order-md-1">
                    <div class="container">
                        <div class="row align-items-center justify-content-center">
                            <div class="col-md-6">
                                <div class="form-block">
                                    <div class="text-center mb-5">
                                        <h3><strong>Aviso</strong></h3>
                                    </div>
                                    <b>
                                    <?php 
                                        $mensagem = new Entrar();
                                        $mensagem->imprimindoAviso();
                                    ?>
                                    </b><br><br>
                                    <a href="../../view/bootstrap/entrar.html"><input type="submit" value="Entrar" class="btn btn-block btn-primary"></a><br>
                                    <a href="/index.html"><input type="submit" value="Voltar a tela inicial" class="btn btn-block btn-primary"></a>                             
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </body>
    </html>