<div class="half">
    <div class="bg order-1 order-md-2" style="background-image: url('./assets/images/bg_1.jpg');"></div>
    <div class="contents order-2 order-md-1">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-6">
            <div class="form-block">
              <div class="text-center mb-5">
                <h3>Micro Framework<strong> Tela Inicial</strong></h3>
              </div>
              <div class="form-group first">
                <label for="username">

                </label>

                <form method="post">
                  <input type="submit" name="botao_criar_conta" value="Criar Conta"
                    class="btn btn-block btn-primary"><br>

                  <input type="submit" name="botao_entrar" value="Entrar" class="btn btn-block btn-primary">
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
